### PR TITLE
Create quantum_number_generation.py

### PR DESCRIPTION
**Pull request by apassenger**
quantum_coin_generation or quantum_number_generation
In this example:
We connect a node (Alice) and create a fresh qubit then apply a Hadamard gate. After measuring the qubit, we repeat the process 10 times(in the for loop)and finally  we create an empty list in order to saving the quantum numbers or coins and the quantum numbers/coins are printed in the screen
Note: Some resources  say quantum random number generation for the process and some resources say quantum coin generation. In my opinion quantum coin generation is a quantum money and I think it is more different process although it has some similar features. To prevent confussion, I explained here

### CODE REVIEW

**Comment by AckslD** [comment]
Hi @apassenger!

There are some linting errors in your code, see the check above.
Furthermore could you add some description of what the example does to the file.
Also it's good to but the code itself in a function or at least in the clause of
`if __name__ == '__main__':`
since then someone can import your function without running the example.

**Comment by apassenger** [comment]
Hi,
I can run my code I cannot see any problem ???(I can compile my code on linux and Python3.6.7)

**Comment by apassenger** [comment]
I think It is ok now!

**Comment by AckslD** [comment]
@apassenger As mentioned above, could you add a description of what this example does and make it possible for someone to import the functionality without running it?

**Comment by apassenger** [comment]
Hi I added description and also I added some knowledge in readme file.

Regarding the functionality I changed the structure of function and name of function as main

**Pull request merged**
