### PR TITLE
Flush remaining headers when exiting cqc context

### PR DESCRIPTION
**Pull request by lgvacanti**
When exiting the cqc context, check whether there are any pending headers. If there are, flush them.

Questions:
1) I've currently put this in `CQCConnection`'s `__exit__()` method, but it could also be put in the `close()` method, which is called by the `__exit__()` method.

2) It would be nice to add a test that tests whether the commands get flushed when exiting the context without having explicitly called `flush()`, but I didn't see how to do that with your current test method, @AckslD , since it has `pend_messages` set to `False`.

### CODE REVIEW

**Comment by AckslD** [comment]
@Shyadow I would say that indeed it should be put in `close` for the case where someone does not use the context.

Regarding the tests, we could have that the function `command_to_apply` (maybe calling it something else) could intead just return a `CQCConnection` which is instantiated in the function and one can then choose what to set for for example `pend_messages`. What do you think?

**Comment by lgvacanti** [comment]
@AckslD Oh, now that you mention that, I realize that there is a method to change what pend_messages is, so I could just call that in the commands to apply function for this test and make it pend messages in that way.

**Comment by lgvacanti** [comment]
@AckslD It should be good now.

**Comment by AckslD** [comment]
Looks good @Shyadow! One thing though, could you put the the tests functions you added in a seperate file/folder and just import them in the base test? I think it would be better to not put everything in a single file although I think it's good to keep one of the tests there to show how it can be written.

**Comment by lgvacanti** [comment]
@AckslD Done. I couldn't think of a great other name for the file, so I called it `help_cqcconnection.py`. If you think of something better let me know.

**Comment by AckslD** [comment]
@lgvacanti I think we could make a folder (e.g. `test_cases_cqcconnection`) in which you could put this file and called it `flush.py` or so

**Comment by lgvacanti** [comment]
@AckslD Done

**Pull request merged**
